<?php declare(strict_types=1);
/**
 * GoogleTagManager plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\ViewModel\Category;

/** @var Template $block */
/** @var Category $categoryViewModel */
try {
    $categoryViewModel = $block->getCategoryViewModel();
    $categoryViewModel->addCategory($categoryViewModel->getCurrentCategory());
} catch (NoSuchEntityException $e) {
    return '';
}
