<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

// phpcs:disable Squiz.WhiteSpace.SuperfluousWhitespace.EndLine
// phpcs:disable PSR2.Files.EndFileNewline.NoneFound

/** @var \Yireo\GoogleTagManager2\Block\Category $block */
$helper = $block->getHelper();
$viewModel = $block->getViewModel();