<?php declare(strict_types=1);

/**
 * GoogleTagManager plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Api\AttributesViewModelInterface;

/** @var Template $block */
/** @var AttributesViewModelInterface $attributesViewModel */
$attributesViewModel = $block->getAttributesViewModel();
