<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;
use Yireo\GoogleTagManager2\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push(<?= /* @noEscape */ $dataLayerJson ?>);
    <?php if ($config->isDebug()): ?>
    require(['yireoGoogleTagManagerLogger'], function (logger) {
        logger('initial state (page)', <?= /* @noEscape */ $dataLayerJson ?>);
    });
    <?php endif; ?>

    <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk): ?>
    <?php if ($config->isDebug()): ?>
    require(['yireoGoogleTagManagerLogger'], function (logger) {
        logger('event (page)', <?= /* @noEscape */ $dataLayerEventsJsonChunk ?>);
    });
    <?php endif; ?>
    window.dataLayer.push(<?= /* @noEscape */ $dataLayerEventsJsonChunk ?>);
    <?php endforeach; ?>
</script>
