<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;
use Yireo\GoogleTagManager2\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push(<?= /* @noEscape */ $dataLayerJson ?>);
    <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk): ?>
    window.dataLayer.push(<?= /* @noEscape */ $dataLayerEventsJsonChunk ?>);
    <?php endforeach; ?>
</script>
<?php if($config->isDebug()): ?>
    <?= $block->getChildBlock('debugging')->setData(['data_layer_view_model' => $dataLayerViewModel])->toHtml() ?>
<?php endif; ?>
