<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;
use Yireo\GoogleTagManager2\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->toJson($dataLayerViewModel->getDataLayer());
$dataLayerEvents = $dataLayerViewModel->getDataLayerEvents();
?>
<script>
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push({ecommerce: null});
    <?php if ($config->isDebug()): ?>
    yireoGtmNotice('initial state (page)', <?= /* @noEscape */ $dataLayerJson ?>);
    <?php endif; ?>
    window.dataLayer.push(<?= /* @noEscape */ $dataLayerJson ?>);
    <?php foreach ($dataLayerEvents as $dataLayerEvent): ?>
    <?php $dataLayerEventJson = $dataLayerViewModel->toJson($dataLayerEvent); ?>
    <?php if ($config->isDebug()): ?>
    yireoGtmNotice('event (page)', <?= /* @noEscape */ $dataLayerEventJson ?>);
    <?php endif; ?>
    window.dataLayer.push(<?= /* @noEscape */ $dataLayerEventJson ?>);
    <?php endforeach; ?>
</script>
