<?php declare(strict_types=1);
/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2019 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Yireo\GoogleTagManager2\Block\Generic;

/** @var Generic $block */
$helper = $block->getHelper();
$viewModel = $block->getViewModel();

// Fetch request information
$moduleName = $block->getRequest()->getModuleName();
$controllerName = $block->getRequest()->getControllerName();
$actionName = $block->getRequest()->getActionName();
$route = $moduleName . '/' . $controllerName . '/' . $actionName;
?>
<?php if ($helper->isEnabled()): ?>
    <?php $block->addAttribute('pageType', $route); ?>
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=<?=  /* @noEscape */ $helper->getId(); ?>"
                height="0" width="0"
                style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        require(['yireoGoogleTagManager'], function(yireoGoogleTagManager) {
            yireoGoogleTagManager.yireoGoogleTagManager(<?=  /* @noEscape */ $block->getJsonConfiguration() ?>);
        })
    </script>
<?php endif; ?>