<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

/** @var \Yireo\GoogleTagManager2\Block\Generic $block */

$moduleName = $block->getRequest()->getModuleName();
$controllerName = $block->getRequest()->getControllerName();
$actionName = $block->getRequest()->getActionName();
$route = $moduleName.'/'.$controllerName.'/'.$actionName;
?>
<?php if ($block->isEnabled()) : ?>
    <?php $block->addAttribute('pageType', $route); ?>
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=<?= $block->getId(); ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script type="text/x-magento-init">
    {
        "*": {
            "yireoGenericGtm": <?php echo $block->getJsonConfiguration() ?>
        }
    }
    </script>
<?php endif; ?>
