<?php declare(strict_types=1);

use Tagging\GTM\Config\Config;

/** @var Config $config */
$config = $block->getConfig();

if ($config->isEnabled() && $config->getGoogleTagmanagerUrl() && strlen($config->getGoogleTagmanagerUrl()) > 0 && $config->isPlacedByPlugin()) {
echo "
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/adex.js'></script>
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/user-data-minified.es.js'></script>
<script defer src='https://{$config->getGoogleTagmanagerUrl()}/settings.js'></script>
";
}
?>