<?php
/**
 * GoogleTagManager plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2017 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

/** @var \Yireo\GoogleTagManager2\Block\Product $block */
$helper = $block->getHelper();
$viewModel = $block->getViewModel();
?>
<?php if ($helper->isEnabled()): ?>
    <?php $product = $block->getProduct(); ?>
    <?php if (!empty($product) && $product->getId() > 0): ?>
        <?php $block->addAttribute('productId', $product->getId()); ?>
        <?php $block->addAttribute('productName', $product->getName()); ?>
        <?php $block->addAttribute('productSku', $product->getSku()); ?>
        <?php $block->addAttribute('productPrice', $product->getPrice()); ?>
    <?php endif; ?>
<?php endif; ?>