<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;

/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
?>

<?php
$events = ($config->waitForUserInteraction() === false)
    ? "'load', 'keydown', 'mouseover', 'scroll', 'touchstart', 'wheel'"
    : "'keydown', 'mouseover', 'scroll', 'touchstart', 'wheel'";
?>
<script>
    window.YIREO_GOOGLETAGMANAGER2_ENABLED = true;
    (function (events) {
        const initYireoGoogleTagManager2 = function () {
            events.forEach(function (eventType) {
                window.removeEventListener(eventType, initYireoGoogleTagManager2);
            });

            (function (w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
                var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s),
                    dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src = '<?= $config->getGoogleTagmanagerUrl() ?>' + '/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', '<?= $config->getId() ?>');
        }

        events.forEach(function (eventType) {
            window.addEventListener(eventType, initYireoGoogleTagManager2, {once: true, passive: true})
        })
    })([<?= $events ?>]);

    <?php if ($config->isDebug()): ?>
    window.YIREO_GOOGLETAGMANAGER2_DEBUG = true;
    window.YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS = <?= $config->isDebugClicks() ? 'true' : 'false' ?>;
    <?php endif; ?>
</script>
