<?php declare(strict_types=1);

/** @version 3.10.1 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;

/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$gtmIds = explode(',', $config->getId());
?>

<?php
$events = ($config->waitForUserInteraction() === false)
    ? "'load', 'keydown', 'mouseover', 'scroll', 'touchstart', 'wheel'"
    : "'keydown', 'mouseover', 'scroll', 'touchstart', 'wheel'";
?>
<script>
    window.YIREO_GOOGLETAGMANAGER2_ENABLED = true;
    (function (events) {
        const initYireoGoogleTagManager2 = function () {
            events.forEach(function (eventType) {
                window.removeEventListener(eventType, initYireoGoogleTagManager2);
            });

            <?php foreach($gtmIds as $gtmId): ?>
            (function (w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({'gtm.start': new Date().getTime(), event: 'gtm.js'});
                var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s),
                    dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src = '<?= $escaper->escapeUrl($config->getGoogleTagmanagerUrl()) ?>' + '/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', '<?= $escaper->escapeHtml($gtmId) ?>');
            <?php endforeach; ?>
        };

        events.forEach(function (eventType) {
            window.addEventListener(eventType, initYireoGoogleTagManager2, {once: true, passive: true})
        });
    })([<?= /* @noEscape */ $events ?>]);

    <?php if ($config->isDebug()): ?>
    window.YIREO_GOOGLETAGMANAGER2_DEBUG = true;
    window.YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS = <?= $config->isDebugClicks() ? 'true' : 'false' ?>;
    <?php endif; ?>
</script>
