<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Api\AttributesViewModelInterface;

/** @var AttributesViewModelInterface $attributes */
/** @var Template $block */
$attributes = $block->getAttributesViewModel();
if (!count($attributes->getAttributes())) {
    return;
}
?>
<script>
window.dataLayer = window.dataLayer || [];
window.dataLayer.push(<?= $attributes->getAttributesAsJson() ?>);
</script>
