<?php declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2019 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Api\AttributesViewModelInterface;
use Yireo\GoogleTagManager2\Api\CommonsViewModelInterface;
use Yireo\GoogleTagManager2\Config\Config;

/** @var Template $block */
/** @var CommonsViewModelInterface $commonsViewModel */
/** @var AttributesViewModelInterface $attributesViewModel */
/** @var Config $config */

$commonsViewModel = $block->getCommonsViewModel();
$attributesViewModel = $block->getAttributesViewModel();
$config = $block->getConfig();

$attributesViewModel->addAttribute('pageType', $commonsViewModel->getPageType());
?>
<noscript>
    <iframe src="//www.googletagmanager.com/ns.html?id=<?= /* @noEscape */
    $config->getId(); ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>

<script type="text/x-magento-init">
    {"*":{"yireoGoogleTagManager":<?=  /* @noEscape */ $commonsViewModel->getJsonConfiguration() ?>}}
</script>
