<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Tagging\GTM\Config\Config;

/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
?>
<script>
    window.Tagging_GTM_ENABLED = true;

    <?php
    if ($config->isEnabled()) {
        echo "window.AdPage_ENABLED_PLUGIN = true;";
    } else {
        echo "window.AdPage_ENABLED_PLUGIN = false;";
    }

    if ($config->isPlacedByPlugin()) {
        echo "window.AdPage_PLACED_BY_PLUGIN = true;";
    } else {
        echo "window.AdPage_PLACED_BY_PLUGIN = false;";
    }

    echo "window.AdPage_PLUGIN_VERSION = '{$config->getVersion()}';";
    ?>

        (function(events) {
            const initgoogleTagManager2 = function() {
                events.forEach(function(eventType) {
                    window.removeEventListener(eventType, initgoogleTagManager2);
                });

                <?php
                if ($config->isEnabled() && $config->isPlacedByPlugin()) {
                    echo $config->getConfig();
                }
                ?>
            }

            events.forEach(function(eventType) {
                window.addEventListener(eventType, initgoogleTagManager2, {
                    once: true,
                    passive: true
                })
            })
        })(['load']);
</script>

<?php if ($config->isDebug()) : ?>
    <script>
        window.Tagging_GTM_DEBUG = true;
    </script>
<?php endif; ?>