<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Api\AttributesViewModelInterface;
use Yireo\GoogleTagManager2\ViewModel\Success;

/** @var Template $block */
/** @var Success $successViewModel */
/** @var AttributesViewModelInterface $attributesViewModel */

$successViewModel = $block->getSuccessViewModel();
$attributesViewModel = $block->getAttributesViewModel();

foreach ($successViewModel->getOrderAttributes() as $name => $value) {
    $attributesViewModel->addAttribute($name, $value);
}
