<?php
/**
 * GoogleTagManager plugin for Magento 
 *
 * @package     Yireo_GoogleTagManager
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2015 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$loadProducts = (int) Mage::helper('googletagmanager')->getConfigValue('category_products');
if ($loadProducts > 0) {
    $productCollection = $this->getLoadedProductCollection();
}
?>
<?php if($this->isEnabled()) : ?>
    <?php $category = $this->getCategory(); ?>
    <?php if(!empty($category) && $category->getId() > 0) : ?>
        <?php $this->addAttribute('categoryId', $category->getId()); ?>
        <?php $this->addAttribute('categoryName', $category->getName()); ?>
    <?php endif; ?>
    <?php if(!empty($productCollection)) : ?>
        <?php $this->addAttribute('categorySize', $productCollection->getSize()); ?>
        <?php $categoryProducts = array(); ?>
        <?php $i = 0; ?>
        <?php foreach($productCollection as $product) : ?>
            <?php if ($i > $loadProducts) break; ?>
            <?php $categoryProduct = array(); ?>
            <?php $categoryProduct['id'] = $product->getId(); ?>
            <?php $categoryProduct['name'] = $product->getName(); ?>
            <?php $categoryProduct['sku'] = $product->getSku(); ?>
            <?php $categoryProduct['price'] = $product->getPrice(); ?>
            <?php $categoryProducts[] = $categoryProduct; ?>
            <?php $i++ ; ?>
        <?php endforeach; ?>
        <?php $this->addAttribute('categoryProducts', $categoryProducts); ?>
    <?php endif; ?>
<?php endif; ?>
