<?php declare(strict_types=1);

/** @version 3.10.1 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Template $block */
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    require(['yireoGoogleTagManagerPush'], function (pusher) {
        pusher(<?= $escaper->escapeHtml($dataLayerJson) ?>, 'push (initial page) [data-layer.phtml]');
        <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk): ?>
        pusher(<?= $escaper->escapeHtml($dataLayerEventsJsonChunk) ?>, 'push (initial event) [data-layer.phtml]');
        <?php endforeach; ?>
    });
</script>
