<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Template $block */
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    require(['yireoGoogleTagManagerLogger'], function (logger) {
        logger('push (initial) [data-layer.phtml]', <?= /* @noEscape */ $dataLayerJson ?>);
    });

    <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk): ?>
    require(['yireoGoogleTagManagerLogger'], function (logger) {
        logger('push (event) [data-layer.phtml]', <?= /* @noEscape */ $dataLayerEventsJsonChunk ?>);
    });
    <?php endforeach; ?>
</script>
