<?php declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2019 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\ViewModel\Commons;

/** @var Template $block */
/** @var Commons $commons */
$commons = $block->getCommonsViewModel();
?>
<script type="text/x-magento-init">
    {"*":{"yireoGoogleTagManager":<?=  /* @noEscape */ $commons->getConfigurationAsJson() ?>}}
</script>

<script>
    require(['jquery'], function($) {
        $('.product-items a.product').click(function(event) {
            const debugClicks = YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS || false;
            const $parent = $(this).parent();
            const regex = /_(\d+)$/;
            const matches = $parent.attr('id').match(regex);
            const productId = matches[1];

            const gtmData = {
                'event': 'select_item',
                'ecommerce': {
                    'items': [{
                        id: productId
                    }]
                }
            }

            yireoGtmNotice('page event "select_item" (js)', gtmData);
            dataLayer.push({ ecommerce: null });
            dataLayer.push(gtmData);

            if (debugClicks && confirm("Press to continue with redirect") === false) {
                event.preventDefault();
            }
        });
    });
</script>
