<?php declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2019 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\ViewModel\Commons;

/** @var Template $block */
/** @var Commons $commons */
$commons = $block->getCommonsViewModel();
$config = $commons->getConfiguration();
?>
<noscript>
    <iframe src="//www.googletagmanager.com/ns.html?id=<?= /* @noEscape */
    $config['id']; ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>

<script type="text/x-magento-init">
    {"*":{"yireoGoogleTagManager":<?=  /* @noEscape */ $commons->getConfigurationAsJson() ?>}}
</script>
