<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\DataLayer\Event\BeginCheckout;

/** @var Template $block */
/** @var BeginCheckout $beginCheckoutEvent */
$beginCheckoutEvent = $block->getData('begin_checkout_event');
$encodedEvent = json_encode($beginCheckoutEvent->get());
?>
<script>
    window.YIREO_GOOGLETAGMANAGER2_BEGIN_CHECKOUT = <?= $encodedEvent ?>;
</script>
