<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;
use Yireo\GoogleTagManager2\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    logger('push (initial page) [data-layer.phtml]', <?= /* @noEscape */ $dataLayerJson ?>);
    <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk): ?>
        logger('push (page-based event) [data-layer.phtml]', <?= /* @noEscape */ $dataLayerEventsJsonChunk ?>);
    <?php endforeach; ?>
</script>
