<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use AdPage\GTM\Config\Config;
use AdPage\GTM\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    googleTagManager2Pusher(<?= /* @noEscape */ $dataLayerJson ?>, 'push (initial page) [data-layer.phtml]');
    <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk): ?>
    googleTagManager2Pusher(<?= /* @noEscape */ $dataLayerEventsJsonChunk ?>, 'push (page-based event) [data-layer.phtml]');
    <?php endforeach; ?>
</script>
