<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Tagging\GTM\Config\Config;
use Tagging\GTM\ViewModel\DataLayer;

/** @var DataLayer $dataLayerViewModel */
/** @var Config $config */
/** @var Template $block */
$config = $block->getConfig();
$dataLayerViewModel = $block->getDataLayerViewModel();
$dataLayerJson = $dataLayerViewModel->getDataLayerAsJson();
$dataLayerEventsJsonChunks = $dataLayerViewModel->getDataLayerEventsAsJsonChunks();
?>
<script>
    function callInitialDataLayer() {
        <?php foreach ($dataLayerEventsJsonChunks as $dataLayerEventsJsonChunk) : ?>
            googleTagManager2Pusher(<?= /* @noEscape */ $dataLayerEventsJsonChunk ?>, 'push (page-based event) [data-layer.phtml]');
        <?php endforeach; ?>
    }

    document.addEventListener("DOMContentLoaded", function() {
        if (window.taggingHelpers) {
            setTimeout(function() {
                callInitialDataLayer();
            }, 100); // Make sure we always sent after user_data
        } else {
            setTimeout(function() {
                if (window.taggingHelpers) {
                    callInitialDataLayer();
                } else {
                    console.log("taggingHelpers not available after wait, sending initial data layer anyway");
                }
            }, 750);
        }
    });

    googleTagManager2Pusher(<?= /* @noEscape */ $dataLayerJson ?>, 'push (initial page) [data-layer.phtml]');
</script>