<?php declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2019 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\ViewModel\Commons;

/** @var Template $block */
/** @var Commons $commons */
$commons = $block->getCommonsViewModel();
?>
<script>
    function yireoGoogleTagManager2FindParentElementWithName(element, parentTagName) {
        if (!element.parentElement) {
            return null;
        }

        if (element.parentElement.tagName.toLowerCase() === parentTagName) {
            return element.parentElement;
        }

        return yireoGoogleTagManager2FindParentElementWithName(element.parentElement, parentTagName);
    }

    const products = document.querySelectorAll('.products a.product');
    if (products) {
        products.forEach(function(product) {
            product.addEventListener('click', function(event, s) {
                let parentElement = yireoGoogleTagManager2FindParentElementWithName(event.target, 'form');
                const inputElement = parentElement.querySelector('input[name="product"]');
                const productId = inputElement.value;
                const productData = window['YIREO_GOOGLETAGMANAGER2_PRODUCT_DATA_ID_' + productId] || {};
                productData.item_id = productId;

                const gtmData = {
                    'event': 'select_item',
                    'ecommerce': {
                        'items': [productData]
                    }
                }

                logger('page event "select_item" (js)', gtmData);
                dataLayer.push(gtmData);

                if (YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS && confirm("Press to continue with redirect") === false) {
                    event.preventDefault();
                }
            });
        })
    }
</script>

<script>
    window.addEventListener('private-content-loaded', function(event) {
        var isEmpty = function (variable) {
            if (typeof variable === 'undefined') {
                return true;
            }

            if (Array.isArray(variable) && variable.length === 0) {
                return true;
            }

            return typeof variable === 'object' && Object.keys(variable).length === 0;
        }

        var getSectionNames = function () {
            return ['cart', 'customer'];
        }

        let attributes = {};
        getSectionNames().forEach(function (sectionName) {
            if (!event.detail.data[sectionName].gtm_events) {
                return;
            }

            const gtmEvents = event.detail.data[sectionName].gtm_events;
            for (const [eventId, eventData] of Object.entries(gtmEvents)) {
                if (eventData.triggered === true) {
                    continue;
                }

                logger('customerData section "' + sectionName + '" contains event "' + eventId + '"', eventData);
                window.dataLayer.push(eventData);

                if (eventData.cacheable !== true) {
                    //delete sectionData['gtm_events'][eventId]; // @todo: Is this still needed?
                    logger('invalidating sections "' + sectionName + '"', eventData)
                }

                eventData.triggered = true;
            }
        });

        logger('initial state (js)', attributes);
        window.dataLayer = window.dataLayer || [];

        if (false === isEmpty(attributes)) {
            window.dataLayer.push(attributes);
        }
    });
</script>
