<?php
declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2023 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\Config\Config;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Config $config */
/** @var HyvaCsp $hyvaCsp */
/** @var Template $block */
$config = $block->getConfig();

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php if ($config->isConsent()): ?>
    <script>
        function initYireoCookieConsentBanner() {
            return {
                showBanner: localStorage.getItem('yireoGoogleTagManager2ConsentBannerIsShowing') !== 'false',
                expanded: 'none',
                modes: JSON.parse(localStorage.getItem('yireoGoogleTagManager2ConsentModes') || '{"necessary": true,"analytics": false,"preferences": false,"marketing": false}'),
                selectedModes: JSON.parse(localStorage.getItem('yireoGoogleTagManager2ConsentModes') || '{"necessary": true,"analytics": true,"preferences": true,"marketing": true}'),
                init() {
                    this.$watch('showBanner', (val) => {
                        console.log('showBanner', val);
                        localStorage.setItem('yireoGoogleTagManager2ConsentBannerIsShowing', val)
                    });
                    this.$watch('modes', (val) => {
                        this.selectedModes = val;
                        localStorage.setItem('yireoGoogleTagManager2ConsentModes', JSON.stringify(val));
                    });
                    this.setConsent(this.modes, 'default');
                },
                updateSelection() {
                    const checkbox = this.$event.target;
                    if (checkbox.checked && ! this.selectedModes[checkbox.value]) {
                        this.selectedModes[checkbox.value] = true;
                    }
                    if (! checkbox.checked && this.selectedModes[checkbox.value]) {
                        this.selectedModes[checkbox.value] = false;
                    }
                },
                isChecked() {
                    return this.selectedModes[this.$el.value];
                },
                learnMore() {
                    const item = this.$el.dataset.mode;
                    this.expanded = this.expanded === item ? 'none' : item;
                },
                pusher() {
                    yireoGoogleTagManager2Pusher(arguments, 'dataLayer (consent) [script-consent.phtml]');
                },
                consentEvent(eventName) {
                    const eventData = {
                        'event': eventName,
                    }
                    yireoGoogleTagManager2Pusher(eventData, 'dataLayer (consent-event) [script-consent.phtml]');
                },
                setConsent(consent, mode = 'update') {
                    const consentMode = {
                        'functionality_storage': consent.necessary ? 'granted' : 'denied',
                        'security_storage': consent.necessary ? 'granted' : 'denied',
                        'ad_storage': consent.marketing ? 'granted' : 'denied',
                        'ad_user_data': consent.marketing ? 'granted' : 'denied',
                        'ad_personalization': consent.marketing ? 'granted' : 'denied',
                        'analytics_storage': consent.analytics ? 'granted' : 'denied',
                        'personalization_storage': consent.preferences ? 'granted' : 'denied',
                    };

                    window.dataLayer = window.dataLayer || [];
                    this.pusher('consent', mode, consentMode);

                    if (mode === 'update') {
                        this.consentEvent('cookieConsentUpdate');
                    } else {
                        this.consentEvent('cookieConsentInitial');
                    }

                    if (consent.necessary) {
                        this.consentEvent('cookieConsentGranted');
                    }
                    if (consent.marketing) {
                        this.consentEvent('cookieConsentMarketingGranted');
                    }
                    if (consent.analytics) {
                        this.consentEvent('cookieConsentAnalyticsGranted');
                    }
                    if (consent.preferences) {
                        this.consentEvent('cookieConsentPreferencesGranted');
                    }

                    this.modes = consent;
                    if (mode === 'update') {
                        this.showBanner = false;
                    }
                },
                setConsentAll() {
                    this.setConsent({
                        necessary: true,
                        analytics: true,
                        preferences: true,
                        marketing: true
                    });
                },
                setConsentRejectAll() {
                    this.setConsent({
                        necessary: true,
                        analytics: false,
                        preferences: false,
                        marketing: false
                    });
                },
                setSelectedConsent() {
                    this.setConsent(this.selectedModes);
                },
                isExpanded() {
                    return this.expanded === this.$el.dataset.mode;
                },
                isShowBanner() {
                    return this.showBanner = true;
                },
                isNotShowBanner() {
                    return this.showBanner = false;
                },
                toggleShowBanner() {
                    return this.showBanner = !this.showBanner;
                }
            };
        }
        window.addEventListener(
            'alpine:init',
            () => Alpine.data('initYireoCookieConsentBanner', initYireoCookieConsentBanner),
            {once: true}
        );
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
    <div id="yireo-cookie-consent-banner"
         class="fixed top-0 left-0 right-0 w-screen h-screen flex lg:items-center justify-center text-left bg-black bg-opacity-50 z-50 overflow-y-scroll"
         x-data="initYireoCookieConsentBanner()"
         x-cloak
         x-show="showBanner"
         @yireo-show-consent-banner.window="isShowBanner"
         @yireo-hide-consent-banner.window="isNotShowBanner"
         @yireo-toggle-consent-banner.window="toggleShowBanner"
    >
        <div class="flex flex-col grow-1">
            <div class="bg-white m-4 p-4 max-w-md shadow-xl">
                <h2 class="text-xl font-medium title-font mb-3 text-primary"><?= $escaper->escapeHtml(__('Cookie settings')) ?></h2>
                <p class="mb-4">
                    <?= $escaper->escapeHtml(__('We use cookies to provide you with the best possible experience. They also allow us to analyze user behavior in order to constantly improve the website for you.')) ?>
                    <?php if ($config->getPrivacyStatementUrl() !== null): ?>
                        <a class="block underline text-secondary" target="_blank"
                           href="<?= $escaper->escapeUrl($config->getPrivacyStatementUrl()) ?>">
                            <?= $escaper->escapeHtml(__('Learn more')) ?>
                        </a>
                    <?php endif; ?>
                </p>
                <div class="w-full border-t border-gray-200 ">
                    <div class="flex items-center flex-row gap-2 py-2">
                        <input name="selected-modes[]" value="necessary" @change="updateSelection" :checked="isChecked" id="yireo-consent-necessary" type="checkbox" disabled/>
                        <label for="yireo-consent-necessary"><?= $escaper->escapeHtml(__('Essential')) ?></label>
                        <button class="text-xs text-slate-400 hover:underline" @click="learnMore" data-mode="necessary">
                            <?= $heroicons->informationCircleHtml("h-4 w-4 border-current inline-flex", 16, 16, ['aria-hidden' => 'true']) ?>
                            <span class="ml-2 sr-only">
                <?= $escaper->escapeHtml(__('Learn more')) ?>
              </span>
                        </button>
                    </div>
                    <div x-cloak x-show="isExpanded" data-mode="necessary" class="text-sm py-2">
                        <?= $escaper->escapeHtml(__('Enables storage that supports the functionality of the website or app, e.g. language settings')) ?>
                    </div>
                </div>
                <div class="w-full border-t border-gray-200">
                    <div class="flex items-center flex-row gap-2 py-2">
                        <input name="selected-modes[]" value="analytics" @change="updateSelection" :checked="isChecked" id="yireo-consent-analytics" type="checkbox"/>
                        <label for="yireo-consent-analytics"><?= $escaper->escapeHtml(__('Analytics')) ?></label>
                        <button class="text-xs text-slate-400 hover:underline" @click="learnMore" data-mode="analytics">
                            <?= $heroicons->informationCircleHtml("h-4 w-4 border-current inline-flex", 16, 16, ['aria-hidden' => 'true']) ?>
                            <span class="ml-2 sr-only">
                <?= $escaper->escapeHtml(__('Learn more')) ?>
              </span>
                        </button>
                    </div>
                    <div x-cloak x-show="isExpanded" data-mode="analytics" class="text-sm py-2">
                        <?= $escaper->escapeHtml(__('Enables storage (such as cookies) related to analytics, e.g. visit duration')) ?>
                    </div>
                </div>
                <div class="w-full border-t border-gray-200">
                    <div class="flex items-center flex-row gap-2 py-2">
                        <input name="selected-modes[]" value="preferences" @change="updateSelection" :checked="isChecked" id="yireo-consent-preferences" type="checkbox"/>
                        <label for="yireo-consent-preferences"><?= $escaper->escapeHtml(__('Preferences')) ?></label>
                        <button class="text-xs text-slate-400 hover:underline" @click="learnMore" data-mode="preferences">
                            <?= $heroicons->informationCircleHtml("h-4 w-4 border-current inline-flex", 16, 16, ['aria-hidden' => 'true']) ?>
                            <span class="ml-2 sr-only">
                <?= $escaper->escapeHtml(__('Learn more')) ?>
              </span>
                        </button>
                    </div>
                    <div x-cloak x-show="isExpanded" data-mode="preferences" class="text-sm py-2">
                        <?= $escaper->escapeHtml(__('Enables storage related to personalisation, e.g. video recommendations')) ?>
                    </div>
                </div>
                <div class="w-full border-y border-gray-200 mb-4">
                    <div class="flex items-center flex-row gap-2 py-2">
                        <input name="selected-modes[]" value="marketing" @change="updateSelection" :checked="isChecked" id="yireo-consent-marketing" type="checkbox"/>
                        <label for="yireo-consent-marketing"><?= $escaper->escapeHtml(__('Marketing')) ?></label>
                        <button class="text-xs text-slate-400 hover:underline" @click="learnMore" data-mode="marketing">
                            <?= $heroicons->informationCircleHtml("h-4 w-4 border-current inline-flex", 16, 16, ['aria-hidden' => 'true']) ?>
                            <span class="ml-2 sr-only">
                <?= $escaper->escapeHtml(__('Learn more')) ?>
              </span>
                        </button>
                    </div>
                    <div x-cloak x-show="isExpanded" data-mode="marketing" class="text-sm py-2">
                        <?= $escaper->escapeHtml(__('Enables storage (such as cookies) related to advertising')) ?>
                    </div>
                </div>
                <div class="flex items-center flex-col lg:flex-row gap-2 py-2">
                    <button @click.prevent="setConsentAll"
                            class="btn btn-primary w-full lg:w-auto "
                    >
                        <span class="text-center w-full"><?= $escaper->escapeHtml(__('Accept All')) ?></span>
                    </button>
                    <button @click.prevent="setSelectedConsent"
                            class="btn btn-secondary w-full lg:w-auto text-center"
                    >
                        <span class="text-center w-full"><?= $escaper->escapeHtml(__('Accept Selection')) ?></span>
                    </button>
                    <button @click.prevent="setConsentRejectAll"
                            class="text-secondary w-full lg:w-auto text-center"
                    >
                        <?= $escaper->escapeHtml(__('Reject All')) ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
