<?php declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2023 Yireo (https://www.yireo.com/)
 * @license     Open Software License
 */

/** @var Template $block */

use Magento\Framework\View\Element\Template;

$productPath = $block->getProductPath();
?>
<script>
    function yireoGoogleTagManager2FindParentElementWithName(element, parentTagName) {
        if (!element.parentElement) {
            return null;
        }

        if (element.parentElement.tagName.toLowerCase() === parentTagName) {
            return element.parentElement;
        }

        return yireoGoogleTagManager2FindParentElementWithName(element.parentElement, parentTagName);
    }

    const products = document.querySelectorAll('<?= $productPath ?>');
    if (products && products.length > 0) {
        products.forEach(function(product) {
            product.addEventListener('click', function(event, s) {
                let parentElement = yireoGoogleTagManager2FindParentElementWithName(event.target, 'form');
                const inputElement = parentElement.querySelector('input[name="product"]');
                const productId = inputElement.value;
                const productData = window['YIREO_GOOGLETAGMANAGER2_PRODUCT_DATA_ID_' + productId] || {};
                productData.item_id = productId;

                const eventData = {
                    'event': 'select_item',
                    'ecommerce': {
                        'items': [productData]
                    }
                }

                yireoGoogleTagManager2Pusher(eventData, 'push (page event "select_item") [script-product-clicks.phtml]');

                if (window['YIREO_GOOGLETAGMANAGER2_DEBUG_CLICKS'] && confirm("Press to continue with redirect") === false) {
                    event.preventDefault();
                }
            });
        })
    }
</script>
