<?php declare(strict_types=1);
?>
<script>
    function googleTagManager2Logger(...args) {
        const debug = window.Tagging_GTM_DEBUG || false;
        if (false === debug) {
            return;
        }

        var color = 'gray';
        if (args[0].toLowerCase().startsWith('push')) {
            color = 'green';
        }

        if (args[0].toLowerCase().startsWith('warning')) {
            color = 'orange';
        }

        var css = 'color:white; background-color:' + color + '; padding:1px;'
        console.log('%cTagging_GTM', css, ...args);
    }
</script>
