<?php declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2023 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<script>
    function googleTagManager2Pusher(eventData, message) {
        window.AdPage_GTM_PAST_EVENTS = window.AdPage_GTM_PAST_EVENTS || [];

        const copyEventData = Object.assign({}, eventData);
        let metaData = {};
        if (copyEventData.meta) {
            metaData = copyEventData.meta;
            delete copyEventData.meta;
        }

        const eventHash = btoa(encodeURIComponent(JSON.stringify(copyEventData)));
        if (window.AdPage_GTM_PAST_EVENTS.includes(eventHash)) {
            googleTagManager2Logger('Warning: Event already triggered', eventData);
            return;
        }

        if (metaData && metaData.allowed_pages && metaData.allowed_pages.length > 0
            && false === metaData.allowed_pages.some(page => window.location.pathname.includes(page))) {
            googleTagManager2Logger('Warning: Skipping event, not in allowed pages', window.location.pathname, eventData);
            return;
        }

        if (!message) {
            message = 'push (unknown) [unknown]';
        }

        googleTagManager2Logger(message, eventData);
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({ecommerce: null});
        window.dataLayer.push(eventData);
        window.AdPage_GTM_PAST_EVENTS.push(eventHash);
    }
</script>
