<?php

declare(strict_types=1);

/**
 * GoogleTagManager2 plugin for Magento
 *
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2023 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<script>
    function googleTagManager2Pusher(eventData, message) {
        window.Tagging_GTM_PAST_EVENTS = window.Tagging_GTM_PAST_EVENTS || [];

        const copyEventData = Object.assign({}, eventData);
        let metaData = {};
        if (copyEventData.meta) {
            metaData = copyEventData.meta;
            delete copyEventData.meta;
        }

        const eventHash = btoa(encodeURIComponent(JSON.stringify(copyEventData)));
        if (window.Tagging_GTM_PAST_EVENTS.includes(eventHash)) {
            googleTagManager2Logger('Warning: Event already triggered', eventData);
            return;
        }

        if (metaData && metaData.allowed_pages && metaData.allowed_pages.length > 0 &&
            false === metaData.allowed_pages.some(page => window.location.pathname.includes(page))) {
            googleTagManager2Logger('Warning: Skipping event, not in allowed pages', window.location.pathname, eventData);
            return;
        }

        if (!message) {
            message = 'push (unknown) [unknown]';
        }

        if (window.taggingHelpers) {
            eventData.marketing = window.taggingHelpers.getMarketingObject();
            eventData.device = window.taggingHelpers.getDeviceInfo();
        }

        if (eventData.marketing) {
            const expires = new Date();
            expires.setTime(expires.getTime() + 7 * 24 * 60 * 60 * 1000);
            document.cookie = `trytagging_user_data=${btoa(JSON.stringify(eventData.marketing))};expires=${expires.toUTCString()};path=/`;
        }

        googleTagManager2Logger(message, eventData);
        window.dataLayer = window.dataLayer || [];
        if (eventData && eventData.ecommerce) {
            window.dataLayer.push({
                ecommerce: null
            });
        }
        window.dataLayer.push(eventData);
        window.Tagging_GTM_PAST_EVENTS.push(eventHash);
    }
</script>