<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\DataLayer\Event\BeginCheckout as BeginCheckoutEvent;
use Yireo\GoogleTagManager2\MageWire\Checkout as CheckoutComponent;

/** @var Template $block */
/** @var BeginCheckoutEvent $beginCheckoutEvent */
/** @var CheckoutComponent $magewire */
$magewire = $block->getData('magewire');
if (false === $magewire->isHyvaCheckoutEnabled()) {
    return;
}

$beginCheckoutEvent = $block->getData('begin_checkout_event');
?>
<div>
    <script>
        function initYireoGoogleTagManagerInHyvaCheckout() {
            "use strict";

            function triggerEvent(event) {
                yireoGoogleTagManager2Pusher(event.detail, 'Hyva Checkout');
            }

            triggerEvent(new CustomEvent('ga:trigger-event', {detail: <?= json_encode($beginCheckoutEvent->get()) ?>}));

            return {
                triggerEvent
            }
        }
    </script>
    <div id="ga-trigger"
         x-data="initYireoGoogleTagManagerInHyvaCheckout()"
         class="hidden"
         @ga:trigger-event.window="triggerEvent($event)"
    ></div>
</div>
